# Nombre del workflow
name: CI

# especificar en que eventos se van a ejecutar las tareas
on:
# Triggers: Activan el flujo de trabajo en eventos de solicitud push o pull, pero solo para la rama "principal"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # permite ejecutar este flujo de trabajo manualmente desde la pestaña Acciones
  workflow_dispatch:

# Ejmeplo de Configuracion de variables de entorno para diferentes programas

     env:
       platform: aws
       region: us-east-1
       account: 123456789

# Una ejecución de flujo de trabajo se compone de uno o más trabajos que se pueden ejecutar de forma secuencial o en paralelo
jobs:
  # Este flujo de trabajo contiene un único trabajo llamado "build"
  build:
    #  tipo de maquina virtual en el que se ejecutará el trabajo
    runs-on: ubuntu-latest

    # Steps(pasos) representan una secuencia de tareas que se ejecutarán como parte del trabajo.
    steps:
      - name: "Mostrar mensaje"
        run: echo "Mostrando mensaje con el comando run"

     # crear otro paso para mostrar las variables de entorno

      - name: "Mostrar variables de entorno previamente definidas arriba"
        run: |
          echo "Valor de la variable platform: $platform"
          echo "Valor de la variable region: $region"
          echo "Valor de la variable cuenta: $account"